version: '3.8'

networks:
  ia_network:
    driver: bridge

volumes:
  mysql_data:
services:
  app:
    build: .
    volumes:
      - ./app:/app
    depends_on:
      - db
    env_file:
      - ./.env
    ports:
      - "22:22"
      - "8501:8501"
    networks:
      - ia_network
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/IAdb.sql:/docker-entrypoint-initdb.d/IAdb.sql
    ports:
      - "3307:3306"
    networks:
      - ia_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    env_file:
      - ./.env
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - ia_network
